// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class MadRocketManResources
{
        public const string leaderboard_planets_reached = "CgkIs-r3kO4CEAIQAg"; // <GPGSID>
        public const string achievement_successful_spin = "CgkIs-r3kO4CEAIQCg"; // <GPGSID>
        public const string achievement_nobody_reads_the_credits = "CgkIs-r3kO4CEAIQDA"; // <GPGSID>
        public const string achievement_200_planets = "CgkIs-r3kO4CEAIQCQ"; // <GPGSID>
        public const string achievement_10_planets = "CgkIs-r3kO4CEAIQAw"; // <GPGSID>
        public const string achievement_ouch = "CgkIs-r3kO4CEAIQCw"; // <GPGSID>
        public const string achievement_20_planets = "CgkIs-r3kO4CEAIQBA"; // <GPGSID>
        public const string achievement_150_planets = "CgkIs-r3kO4CEAIQCA"; // <GPGSID>
        public const string achievement_100_planets = "CgkIs-r3kO4CEAIQBw"; // <GPGSID>
        public const string achievement_first_successful_launch = "CgkIs-r3kO4CEAIQAQ"; // <GPGSID>
        public const string achievement_50_planets = "CgkIs-r3kO4CEAIQBg"; // <GPGSID>
        public const string achievement_30_planets = "CgkIs-r3kO4CEAIQBQ"; // <GPGSID>

}

